const propertyMap = {
  "community": {
    "community-african-american": "African American community",
    "community-api": "Asian/Pacific Islander community",
    "community-arab": "Arab community",
    "community-asylum-seeker": "Asylum seekers",
    "community-christian": "Christian community",
    "community-disabled": "People with disabilities",
    "community-domestic-violence-victim-survivor": "Survivors of domestic violence",
    "community-fathers": "Fathers",
    "community-foster-youth": "Foster youth",
    "community-human-trafficking-victim-survivor": "Human trafficking survivors",
    "community-hiv-aids": "Individuals with HIV/AIDS",
    "community-immigrant": "Immigrant community",
    "community-jewish": "Jewish community",
    "community-latino": "Latino community",
    "community-lgbt": "LGBT community",
    "community-military-families": "Military families",
    "community-mothers": "Mothers",
    "community-muslim": "Muslim community",
    "community-native-american": "Native American community",
    "community-parents": "Parents",
    "community-post-incarceration": "Formerly incarcerated individuals",
    "community-pregnant": "pregnant mothers",
    "community-public-transit-riders": "Riders of public transit",
    "community-transitional-age-youth": "Transitional age youth",
    "community-refugee": "Refugees",
    "community-veteran": "Military veterans",
    "community-seniors": "Seniors",
    "community-children": "Children",
    "community-daca-recipient-seeker": "DACA Recipient Seeker",
    "community-detained-immigrant":"Detained tmmigrants"
  },
  "language": {
    "lang-american-sign-language": { name: "American Sign Language" },
    "lang-all-languages-by-interpreter": { name: "Translation services available. Contact organization for more information."},
    "lang-amharic": { code: "am" },
    "lang-arabic": { code: "ar" },
    "lang-bangali": { code: "bn" },
    "lang-berber": { name: "Berber" },
    "lang-bosnian": { code: "bs" },
    "lang-burmese": { code: "my" },
    "lang-cambodian": { code: "km" },
    "lang-cantonese": { code: "zh" },
    "lang-cebuano": { name: "Cebuano" },
    "lang-chiu-chow": { name: "Chiuchow" },
    "lang-croatian": { code: "hr" },
    "lang-fukinese": { name: "Fukinese" },
    "lang-dari": { name: "Dari" },
    "lang-eritrean": { code: "aa" },
    "lang-farsi": { code: "fa" },
    "lang-indonesian": { code: "id" },
    "lang-french": { code: "fr" },
    "lang-german": { code: "de" },
    "lang-greek": { code: "el" },
    "lang-hindi": { code: "hi" },
    "lang-hmong": { name: "Hmong" },
    "lang-italian": { code: "it" },
    "lang-japanese": { code: "ja" },
    "lang-karen": { name: "Karen" },
    "lang-karenni": { name: "Karenni" },
    "lang-khmer": { code: "km" },
    "lang-bhutanese": { code: "dz" },
    "lang-fiji": { code: "fj" },
    "lang-armenian": { code: "hy" },
    "lang-ukrainian": { code: "uk" },
    "lang-korean": { code: "ko" },
    "lang-laotian": { code: "lo" },
    "lang-Ilocano": { name: "Iloko" },
    "lang-mandarin": { code: "zh" },
    "lang-mien": { name: "Mien" },
    "lang-mongolian": { code: "mn" },
    "lang-nepali": { code: "ne" },
    "lang-pashtu": { code: "ps" },
    "lang-portuguese": { code: "pt" },
    "lang-punjabi": { code: "pa" },
    "lang-russian": { code: "ru" },
    "lang-samoan": { code: "sm" },
    "lang-senufu": { name: "Senufo" },
    "lang-serbian": { code: "sr" },
    "lang-spanish": { code: "es" },
    "lang-tagalog": { code: "tl" },
    "lang-telugu": { code: "te" },
    "lang-thai": { code: "th" },
    "lang-tibetan": { code: "bo" },
    "lang-tigrigna": { code: "ti" },
    "lang-tigrinya": { code: "ti" },
    "lang-tongan": { code: "to" },
    "lang-urdu": { code: "ur" },
    "lang-vietnamese": { code: "vi" },
    "lang-wolof": { code: "wo" },
  }


};

export default propertyMap;