const propertyMap = {
  'additional-info': {
    'ada-accessible': 'American Disabilities Act (ADA) accessible',
    'ada-accessible-notes': '[value]',
    'geo-neighborhood': 'Neighborhood: [value]',
    'geo-near-public-transit': 'Close to public transit',
    'geo-public-transit-description': 'Transit details: [value]',
    'time-appointment-required': 'Appointment needed',
    'time-walk-in': 'Walk-ins welcome',
  },
  community: {
    'community-adults': 'Adults (18+)',
    'community-african-american': 'African American community',
    'community-api': 'Asian/Pacific Islander community',
    'community-arab': 'Arab community',
    'community-asylum-seeker': 'Asylum seekers',
    'community-children': 'Children',
    'community-christian': 'Christian community',
    'community-daca-recipient-seeker': 'DACA Recipient Seeker',
    'community-detained-immigrant': 'Detained Immigrants',
    'community-disabled': 'People with disabilities',
    'community-domestic-violence-victim-survivor':
      'Survivors of domestic violence',
    'community-fathers': 'Fathers',
    'community-foster-youth': 'Foster youth',
    'community-hiv-aids': 'Individuals with HIV/AIDS',
    'community-homeless': 'Homeless individuals',
    'community-human-trafficking-victim-survivor':
      'Human trafficking survivors',
    'community-immigrant': 'Immigrant community',
    'community-jewish': 'Jewish community',
    'community-latino': 'Latino community',
    'community-lgbt': 'LGBT community',
    'community-military-families': 'Military families',
    'community-mothers': 'Mothers',
    'community-muslim': 'Muslim community',
    'community-native-american': 'Native American community',
    'community-parents': 'Parents',
    'community-post-incarceration': 'Formerly incarcerated individuals',
    'community-pregnant': 'pregnant mothers',
    'community-public-transit-riders': 'Riders of public transit',
    'community-refugee': 'Refugees',
    'community-seniors': 'Seniors',
    'community-teens': 'Teens',
    'community-transgender':
      'Transgender, non-binary and gender non-conforming community',
    'community-transitional-age-youth': 'Transitional age youth',
    'community-undocumented': 'Undocumented community',
    'community-veteran': 'Military veterans',
  },
  eligibility: {
    'elig-age-or-over': 'Ages [value] or older',
    'elig-age-or-under': 'Ages [value] or under',
    'elig-annual-income-or-over': 'Annual income of $[value] or more',
    'elig-annual-income-or-under': 'Annual income of $[value] or less',
    'elig-asylee': 'Asylee',
    'elig-ca-healthy-families': 'California Healthy Families',
    'elig-city-resident': 'City residents',
    'elig-county-resident': 'Country residents',
    'elig-daca-recipient': 'DACA Recipient',
    'elig-description': '[value]',
    'elig-detained-immigrant': 'Detained immigrant',
    'elig-employed-full-time': 'Full-time employment',
    'elig-employed-part-time': 'Part-time employment',
    'elig-gender': '[value]',
    'elig-grade-or-over': 'Grade [value] or above',
    'elig-grade-or-under': 'Grade [value] or below',
    'elig-homeless': 'Homeless',
    'elig-household-over18-count':
      'Household with more than [value] children under 18 years of age',
    'elig-household-under18-count':
      'Household with less than [value] children under 18 years of age',
    'elig-immigrant': 'Immigrant',
    'elig-legal-resident': 'Legal resident',
    'elig-liheap': 'Low Income Home Energy Assistance Program (LIHEAP)',
    'elig-married': 'Married',
    'elig-medicaid': 'On medicaid',
    'elig-monthly-income': 'Monthly income of $[value]',
    'elig-rent-home': 'Renting home',
    'elig-single-parent': 'Single parent',
    'elig-snap': 'Supplemental Nutrition Assistance Program (SNAP)',
    'elig-ssi': 'Receiving Social Security or SSI',
    'elig-tanf': 'Temporary Assistance for Needy Families (TANF)',
    'elig-undocumented': 'Undocumented immigrant',
    'elig-unknown': 'Unknown',
    'elig-us-citizen': 'U.S. citizen',
    'elig-veteran': 'Militart veteran',
    'elig-wic': 'WIC',
  },
  language: {
    'lang-american-sign-language': {name: 'American Sign Language'},
    'lang-all-languages-by-interpreter': {
      name: '',
    },
    'lang-albanian': {code: 'sq'},
    'lang-amharic': {code: 'am'},
    'lang-arabic': {code: 'ar'},
    'lang-armenian': {code: 'hy'},
    'lang-bangali': {code: 'bn'},
    'lang-berber': {name: 'Berber'},
    'lang-bhutanese': {code: 'dz'},
    'lang-bosnian': {code: 'bs'},
    'lang-bulgarian': {code: 'bg'},
    'lang-burmese': {code: 'my'},
    'lang-cambodian': {code: 'km'},
    'lang-cantonese': {name: 'Cantonese'},
    'lang-cebuano': {name: 'Cebuano'},
    'lang-chin': {name: 'Chin'},
    'lang-chiu-chow': {name: 'Chiuchow'},
    'lang-creole': {name: 'Creole'},
    'lang-croatian': {code: 'hr'},
    'lang-dari': {name: 'Dari'},
    'lang-dinka': {name: 'Dinka'},
    'lang-eritrean': {code: 'aa'},
    'lang-farsi': {code: 'fa'},
    'lang-fiji': {code: 'fj'},
    'lang-french': {code: 'fr'},
    'lang-fukinese': {name: 'Fukinese'},
    'lang-indonesian': {code: 'id'},
    'lang-german': {code: 'de'},
    'lang-greek': {code: 'el'},
    'lang-gujarati': {name: 'Gujarati'},
    'lang-hebrew': {code: 'he'},
    'lang-hindi': {code: 'hi'},
    'lang-hmong': {name: 'Hmong'},
    'lang-hunan': {name: 'Hunan'},
    'lang-hungarian': {code: 'hu'},
    'lang-ilocano': {name: 'Iloko'},
    'lang-italian': {code: 'it'},
    'lang-japanese': {code: 'ja'},
    'lang-karen': {name: 'Karen'},
    'lang-karenni': {name: 'Karenni'},
    'lang-katchi': {name: 'Katchi'},
    'lang-khmer': {code: 'km'},
    'lang-kirundi': {name: 'Kirundi'},
    'lang-kiswahili': {name: 'Kiswahili'},
    'lang-korean': {code: 'ko'},
    'lang-kurdish': {code: 'ku'},
    'lang-kurmanji': {name: 'Kurmanji'},
    'lang-laotian': {code: 'lo'},
    'lang-lingala': {code: 'ln'},
    'lang-mam': {name: 'Mayan (Mam)'},
    'lang-mandarin': {code: 'zh'},
    'lang-mandingo': {name: 'Mandingo'},
    'lang-marathi': {code: 'mr'},
    'lang-mien': {name: 'Mien'},
    'lang-mongolian': {code: 'mn'},
    'lang-nepali': {code: 'ne'},
    'lang-pashtu': {code: 'ps'},
    'lang-polish': {code: 'pl'},
    'lang-portuguese': {code: 'pt'},
    'lang-punjabi': {code: 'pa'},
    'lang-quechua': {code: 'qu'},
    'lang-romanian': {code: 'ro'},
    'lang-russian': {code: 'ru'},
    'lang-samoan': {code: 'sm'},
    'lang-senufu': {name: 'Senufo'},
    'lang-serbian': {code: 'sr'},
    'lang-sinhala': {code: 'si'},
    'lang-somali': {code: 'so'},
    'lang-spanish': {code: 'es'},
    'lang-tagalog': {code: 'tl'},
    'lang-taiwanese': {name: 'Taiwanese'},
    'lang-tamil': {code: 'ta'},
    'lang-telugu': {code: 'te'},
    'lang-thai': {code: 'th'},
    'lang-tibetan': {code: 'bo'},
    'lang-tigrigna': {code: 'ti'},
    'lang-tigrinya': {code: 'ti'},
    'lang-toisanese': {name: 'Toisanese'},
    'lang-tongan': {code: 'to'},
    'lang-turkish': {code: 'tr'},
    'lang-twi': {code: 'tw'},
    'lang-ukrainian': {code: 'uk'},
    'lang-urdu': {code: 'ur'},
    'lang-vietnamese': {code: 'vi'},
    'lang-wolof': {code: 'wo'},
  },
  'more-about': {
    'accepts-medicaid': 'Accepts Medicaid',
    'cost-fees': 'Costs: [value]',
    'cost-free': 'Free of cost',
    'cost-sliding-scale': 'Costs: sliding scale based on income',
    'cost-suggested-donation': 'Costs: suggested donation',
    'has-confidentiality-policy': 'Has a confidentiality policy',
  },
  required: {
    'req-medical-insurance': 'Medical insurance',
    'req-photo-id': 'Photo ID',
    'req-proof-of-age': 'Proof of age',
    'req-proof-of-income': 'Proof of income',
    'req-proof-of-residence': 'Proof of residence',
    'req-referral': 'Referral',
  },
};

export default propertyMap;

export const propertyMapKeys = Object.keys(propertyMap).reduce(
  (result, key, index) => {
    const properties = propertyMap[key];

    result[key] = Object.keys(properties);

    return result;
  },
  {}
);
